<a href="https://colab.research.google.com/github/GauthamAjayKannan/coding/blob/master/AIWORKSHOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello world")

hello world


In [0]:
import numpy as np

In [0]:
a=[[3,5,6],[2,4,5],[3,5,2]]

In [0]:
a=np.array(a)

In [5]:
print(a)

[[3 5 6]
 [2 4 5]
 [3 5 2]]


In [6]:
a.shape

(3, 3)

In [7]:
a.reshape(3,3)

array([[3, 5, 6],
       [2, 4, 5],
       [3, 5, 2]])

In [8]:
a.reshape(9,1,1,1)

array([[[[3]]],


       [[[5]]],


       [[[6]]],


       [[[2]]],


       [[[4]]],


       [[[5]]],


       [[[3]]],


       [[[5]]],


       [[[2]]]])